export const POST_ARTICLE_REQUEST = "POST_ARTICLE_REQUEST"
export const POST_ARTICLE_FAILURE = "POST_ARTICLE_FAILURE"
export const POST_ARTICLE_SUCCESS = "POST_ARTICLE_SUCCESS"

export const FETCH_BATCHES_REQUEST = "FETCH_BATCHES_REQUEST"
export const FETCH_BATCHES_FAILURE = "FETCH_BATCHES_FAILURE"
export const FETCH_BATCHES_SUCCESS = "FETCH_BATCHES_SUCCESS"