export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"

export const LOG_OUT = "LOG_OUT"