export const UPDATE_CORRECT_PREDICTIONS = "UPDATE_CORRECT_PREDICTIONS"
export const REMOVE_CORRECT_PREDICTIONS = "REMOVE_CORRECT_PREDICTIONS"
export const LOADING_FINISHED = "LOADING_FINISHED"
export const CLEAR_ANALYSIS = "CLEAR_ANALYSIS"